### ISSUE TITLE
Aucun probleme, juste un retour

### ISSUE THREAD

**Issue by keusta** [vincedubroeucq/kawi#3]
un petit conseil de graphiste, la lecture sur grand écran (1920w) avec ce thème est pénible car on compte une centaine de signes par ligne.

Le confort de lecture se situe entre 60/70 signes par ligne (caractères + espace compris). 
Il existe une méthode responsive pour afficher du texte en respectant ce ratio :
https://codepen.io/keusta/pen/GRpmoOw (forké, l'original n'est pas de moi)

Je me suis dit que ça pourrait vous servir.
:)

**Comment by vincedubroeucq** [comment]
Merci !
J'ai 92 caractères sur cette page : https://vincentdubroeucq.com/comment-creer-page-de-reglages-extension-wordpress/
J'ai prévu d'ajouter une option pour ajuster la largeur de la zone de contenu. Donc les 

J'ai cappé la largeur en fonction de la taille de police, mais il y a un petit bump que j'ai raté entre 1280 et 1600. Là, ça fait une grande ligne lol. Au dessus de 1600, la police grandit donc ça va.
Je vais retoucher ça.

Calculer la font size en fonction de la largeur de l'écran, c'est no.
Ca donne des fractions de pixels qui sont arrondis différemment selon les navigateurs.
Idem pour le rythme vertical. J'avoue que je ne me suis pas trop attardé sur le rythme vertical. C'est beaucoup de calcul et pinaillage pour très peu de valeur ajoutée. La mesure c'est bien plus important.

En tout cas, bien vu et merci !
